# Generated by Django 2.2.4 on 2019-12-08 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('code', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('latitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'NA'), (1, 'FINISHED'), (2, 'INTRANSIT'), (3, 'CANCELLED'), (4, 'FUTURE')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField()),
                ('passport_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=50)),
                ('plane_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('discount_code', models.IntegerField()),
                ('discount_percent', models.IntegerField()),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Booking')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Luggage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_arrival', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_of_boarding', models.DateTimeField(default=django.utils.timezone.now)),
                ('stay_time', models.DurationField()),
                ('cost', models.IntegerField()),
                ('business_capacity', models.IntegerField()),
                ('economy_capacity', models.IntegerField()),
                ('buisness_vacant', models.IntegerField()),
                ('economy_vacant', models.IntegerField()),
                ('flight_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_from', to='console.Airport')),
                ('flight_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_to', to='console.Airport')),
                ('plane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Plane')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Citizen'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Flight'),
        ),
    ]
