# Generated by Django 2.2.4 on 2019-12-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='code',
        ),
    ]
