# Generated by Django 2.2.4 on 2019-12-08 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='code',
            new_name='name',
        ),
    ]
