# Generated by Django 2.2.4 on 2019-12-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_remove_airport_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='name',
            new_name='code',
        ),
    ]
