# Generated by Django 2.2.4 on 2019-08-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_qrdata_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='', max_length=100)),
                ('device_name', models.CharField(default='', max_length=100)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('inrange', models.BooleanField(default=False)),
            ],
        ),
    ]
