# Generated by Django 2.2.4 on 2019-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_auto_20191208_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airports',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
