# Generated by Django 2.2.4 on 2019-08-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_phonedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonedetail',
            old_name='lat',
            new_name='center_lat',
        ),
        migrations.RenameField(
            model_name='phonedetail',
            old_name='lon',
            new_name='center_lon',
        ),
        migrations.AddField(
            model_name='phonedetail',
            name='device_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='phonedetail',
            name='device_lon',
            field=models.FloatField(default=0),
        ),
    ]
